# DataRoot University DS100 Test #2 Second Try
На проходження тесту виділяється 59 хвилин.

## Python

### 1.  Напишіть ф-цію - генератор паролів. Будьте креативними в тому, як ви створюєте паролі - сильні паролі містять малі та великі літери, цифри та символи. Паролі повинні бути випадковими. Ф-ція повинна створювати новий пароль кожного разу при її виклику. Ф-ція приймає параметр n (n > 6), який відповідає за довжину паролю.

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

In [33]:
import random
import string

def foo(N):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N))

### 2.  Реалізуйте ф-цію, яка перевіряє, чи є слово паліндромом:

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

### 3. Напишіть програму, яка приймає 2 невід'ємні цифри, X, Y як вхід і генерує 2-мірний масив. Значення елемента в i-му рядку і j-му стовпчику масиву має бути i * j, де i = 0, 1 .., X-1; j = 0, 1, .., Y-1.

Приклад:
Припустімо, що до програми наведені наступні входи:
3,5. 
Виходом програми має бути:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

### 4. Реалізуйте клас Torus, який створюється за двома радіусами r, R, R > r. Містить два методи, які повертають відповідно: площу поверхні та об'єм.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 6хв
```

In [ ]:
import math
class Torus:
    
    
    def init(self, R, r):
        self.Radius = R 
        self.radius = r
 
    def S(self):
        return 4 * math.pi**2 * self.Radius * self.radius
    
    def V(self):
        return 2 * math.pi**2 * self.Radius * self.radius**2
    
    
 
 
figure = Torus(10, 5)
print(figure.S())       
print(figure.V())

### 5.  Реалізуйте декоратор, який засікає час виконання ф-ції та логує його.

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

In [ ]:
from functools import wraps
from time import time


def timing(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        start = time()
        result = f(*args, **kwargs)
        end = time()
        print 'Elapsed time: {}'.format(end-start)
        return result
    return wrapper

@timing
def f(a):
    for _ in range(a):
        pass

print(f(2000000))

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Помножте масив розмірності (5, 5, 3), на масив розмірності (5,5).
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

In [5]:
import numpy as np
x = np.random.randn(5, 5, 3)
print(x)
y = np.random.randn(5, 5)
s = np.dot(x, y)

[[[ 0.93766495  0.14767726 -0.26759653]
  [-2.25727432 -1.2676909  -0.19281929]
  [ 0.45762075 -0.17339185  0.56391204]
  [-0.74798026  1.12589115 -0.90050942]
  [ 0.25489335 -1.39127747  0.38363406]]

 [[-0.65953522 -0.60002329 -1.38602538]
  [-0.07533401 -0.31381836  0.67438629]
  [ 0.5108139  -0.36974275  0.48222803]
  [-0.15556145 -1.96389079 -0.45449042]
  [-1.71805824 -0.63179826 -0.98873463]]

 [[ 1.03431818 -1.10120418 -1.40513884]
  [ 0.40814312 -1.82601916 -0.52251329]
  [ 0.5657284  -0.06813954  0.21951406]
  [ 0.76665524 -1.43314049  0.64785632]
  [ 0.59754532 -1.12199937 -0.78729795]]

 [[-0.89321423 -0.15750315  1.48216658]
  [ 0.3062457  -1.16787653 -1.84575423]
  [-0.118169   -0.0212038   0.66698888]
  [ 0.88384438  0.82177612 -0.5374737 ]
  [ 0.99420458 -1.78256396 -0.62270877]]

 [[ 0.71719767  1.9408755  -0.07773577]
  [ 0.58246586  1.96238536 -0.73910109]
  [ 0.70134348 -2.73911344  0.35423903]
  [ 0.07211835 -0.79344013  1.54164817]
  [-0.67389629  0.89323178  0.20

ValueError: shapes (5,5,3) and (5,5) not aligned: 3 (dim 2) != 5 (dim 0)

### 7. Поверніть з 2-вимірного масиву лінійно незалежні рядки.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 6хв
```

### 8. Створіть випадковий вектор розміру 20 і замініть мінімальне за модулем значення на 0
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

In [6]:
vec = np.random.random(20)
print(vec)
vec[np.argmin(vec)] = 0
print(vec)

[ 0.92341378  0.19403016  0.39667704  0.04267008  0.73786659  0.51472191
  0.3003795   0.32737733  0.95967968  0.38220482  0.59177243  0.46686445
  0.25913095  0.17317018  0.73299916  0.28062159  0.61525385  0.00350672
  0.440062    0.71922657]
[ 0.92341378  0.19403016  0.39667704  0.04267008  0.73786659  0.51472191
  0.3003795   0.32737733  0.95967968  0.38220482  0.59177243  0.46686445
  0.25913095  0.17317018  0.73299916  0.28062159  0.61525385  0.          0.440062
  0.71922657]


### Pandas

### 9. Скажімо, є DataFrame df зі стовпчиком "A" цілих чисел. Наприклад:


In [8]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

Відфільтруйте рядки, які містять таке ж число, як рядок, що безпосередньо вище.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

### 10. Скажімо, є DataFrame df з числовими значеннями:

In [9]:
df = pd.DataFrame(np.random.random(size=(5, 3)))

Відніміть середнє значення рядку від кожного елементу у відповідному рядку.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

In [11]:
df

0         1         2
0  0.643759  0.159736  0.858409
1  0.584796  0.634707  0.051834
2  0.682184  0.269142  0.753773
3  0.761176  0.125702  0.680901
4  0.464113  0.505112  0.038437

### 11. Є DataFrame df зі стовпцями: групи - "grps" та значення - "vals":

In [19]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

Для кожної групи знайдіть суму трьох найбільших значень.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

In [31]:
gb = df[["grps","vals"]]
gb.groupby('grps').sum()

vals
grps      
a      416
b      160
c      380

## Scipy & Matplotlib

### 12. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами(завдання на повторення):

#### 12.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sts
%matplotlib inline
mu = 2.0
sigma = 0.5
norm_rv = sts.norm(loc=mu, scale=sigma)

norm_rv.rvs(size=10)

x = np.linspace(0,4,100)
pdf = norm_rv.pdf(x)
plt.plot(x, pdf)

plt.ylabel('$f(x)$')
plt.xlabel('$x$')

#### 12.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [ ]:
bernoulli_rv = sts.bernoulli(0.7)

bernoulli_rv.rvs(10)

x = np.linspace(0,20,21)
cdf = bernoulli_rv.cdf(x)
plt.step(x, cdf)

plt.ylabel('$F(x)$')
plt.xlabel('$x$')

#### 12.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [ ]:
x = np.linspace(0,20,21)
cdf = binomial_rv.cdf(x)
plt.step(x, cdf)

plt.ylabel('$F(x)$')
plt.xlabel('$x$')

#### 12.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [ ]:
poisson_rv = sts.poisson(5)
poisson_rv.rvs(10)
x = np.linspace(0,30,31)
for l in [1, 5, 10, 15]:
    rv = sts.poisson(l)
    cdf = rv.cdf(x)
    plt.step(x, cdf, label="$\lambda=%s$" % l)
plt.legend()
plt.title("CDF (poisson)")

plt.ylabel('$F(x)$')
plt.xlabel('$x$')